dist: bionic
language: python

python:
    - 2.7
    - 3.6
    - 3.7
    - 3.8

before_install:
    - sudo apt-get install -qq python-coverage
    - sudo apt-get install -qq python-pyopencl

install:
    - pip install python-coveralls
    - pip install -r requirements.txt
    - pip install .

script:
    - nosetests -a '!opencl' --with-coverage --cover-package=syris syris

after_success:
    - coveralls
